name: CI

on:
  workflow_dispatch: # allows manual triggering
    inputs:
      create_release:
        description: "Create new release"
        required: true
        type: boolean
  push:
    paths: [".github/workflows/**", "Sources/**/*", "Package.swift"]
  pull_request:
    types:
      [
        opened,
        synchronize,
        edited,
        reopened,
        review_requested,
        ready_for_review,
      ]
    paths: ["Sources/**/*", "Package.swift"]

env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

jobs:
  macOS-latest-make:
    runs-on: macos-latest

    steps:
      - name: Clone
        id: checkout
        uses: actions/checkout@v1

      - name: Dependencies
        id: depends
        run: |
          brew update

      - name: Build
        id: swift_build
        run: |
          swift build
