name: CI

on:
  workflow_dispatch: # allows manual triggering
    inputs:
      create_release:
        description: "Create new release"
        required: true
        type: boolean
  push:
    paths: [".github/workflows/**", "Sources/**/*", "Package.swift"]
  pull_request:
    types:
      [
        opened,
        synchronize,
        edited,
        reopened,
        review_requested,
        ready_for_review,
      ]
    paths: ["Sources/**/*", "Package.swift"]

env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

jobs:
  swift-build:
    runs-on: macos-latest
    steps:
      - name: Clone repo
        id: checkout
        uses: actions/checkout@v1
      - name: Update dependencies
        id: depends
        run: |
          brew update
      - name: Swift build
        id: swift_build
        run: |
          swift build
  xcodebuild:
    runs-on: macos-latest
    strategy:
      matrix:
        platform:
          - macOS
          - iOS
    steps:
      - name: Clone repo
        id: checkout
        uses: actions/checkout@v1
      - name: Update dependencies
        id: depends
        run: |
          brew update
      - name: Xcodebuild
        uses: mxcl/xcodebuild@v1
        with:
          platform: ${{ matrix.platform }}
          action: build
          configuration: release
